import React, { useState, useRef, useEffect } from 'react';
import { 
  FileText, 
  Copy, 
  Check, 
  Download, 
  Send, 
  Sparkles, 
  Layers, 
  BookOpen, 
  ExternalLink,
  HelpCircle,
  Clock,
  Eye
} from 'lucide-react';
import { DocumentAnalysis, ChatMessage, ParsedDocument } from '../types';

interface AnalysisResultViewProps {
  document: ParsedDocument;
  analysis: DocumentAnalysis;
  chatMessages: ChatMessage[];
  onAskQuestion: (question: string) => Promise<void>;
  isAsking: boolean;
}

export const AnalysisResultView: React.FC<AnalysisResultViewProps> = ({
  document,
  analysis,
  chatMessages,
  onAskQuestion,
  isAsking,
}) => {
  const [questionInput, setQuestionInput] = useState('');
  const [copiedSummary, setCopiedSummary] = useState(false);
  const [showRawTextModal, setShowRawTextModal] = useState(false);
  const chatBottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (chatMessages.length > 0) {
      chatBottomRef.current?.scrollIntoView({ behavior: 'smooth' });
    }
  }, [chatMessages, isAsking]);

  const handleCopySummary = () => {
    const fullText = `PRÉCIS DOCUMENT BRIEF: ${analysis.fileName}
Type: ${analysis.documentType} | Pages: ${analysis.pageCount} | Words: ${analysis.wordCount}

SUMMARY:
${analysis.summary}

KEY POINTS:
${analysis.keyPoints.map((kp, i) => `${i + 1}. ${kp}`).join('\n')}

TOPICS:
${analysis.topics.join(', ')}`;

    navigator.clipboard.writeText(fullText);
    setCopiedSummary(true);
    setTimeout(() => setCopiedSummary(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const content = `# Document Brief: ${analysis.fileName}
*Analyzed with Précis on ${analysis.extractedAt}*

- **Document Type:** ${analysis.documentType}
- **Length:** ${analysis.pageCount} page${analysis.pageCount > 1 ? 's' : ''} (~${analysis.wordCount.toLocaleString()} words)
- **Estimated Reading Time:** ~${analysis.readingTimeMinutes || 2} min

---

## ✦ Executive Summary

${analysis.summary}

---

## ✦ Key Points & Takeaways

${analysis.keyPoints.map((point) => `- **${point}**`).join('\n\n')}

---

## ✦ Topics & Themes

${analysis.topics.map((t) => `\`#${t}\``).join('  ')}

---
*Generated by Précis Document Intelligence*
`;

    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = window.document.createElement('a');
    a.href = url;
    a.download = `${analysis.fileName.replace(/\.[^/.]+$/, '')}_Precis_Brief.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleSubmitQuestion = (e: React.FormEvent) => {
    e.preventDefault();
    if (!questionInput.trim() || isAsking) return;
    const q = questionInput.trim();
    setQuestionInput('');
    onAskQuestion(q);
  };

  const handlePromptChipClick = (prompt: string) => {
    if (isAsking) return;
    onAskQuestion(prompt);
  };

  const quickPrompts = [
    'Summarize this in one sentence',
    'What are the key takeaways?',
    'Who or what is this document about?',
    'What are the main risks, requirements, or limitations?',
  ];

  // Helper topic colors for variety
  const topicColorStyles = [
    'bg-[#EBF5EE] text-[#1E5D38] border-[#D2EADA]',
    'bg-[#FEF5E7] text-[#8C5500] border-[#FBE3B8]',
    'bg-[#EEF4FB] text-[#1D5288] border-[#D4E4F7]',
    'bg-[#F5EFFB] text-[#5D2B86] border-[#E8DAF6]',
    'bg-[#F8F4EC] text-[#554E41] border-[#E5DFD1]',
  ];

  return (
    <div className="w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 sm:py-8 flex flex-col gap-6">
      
      {/* Top Document Meta Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-[#E8E2D6]">
        {/* Document Name & Page Stats */}
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-[#EFEAE0] border border-[#DDD6C8] flex items-center justify-center text-[#4A443A] shrink-0 shadow-2xs">
            <FileText className="w-5 h-5" />
          </div>
          <div className="flex flex-col">
            <h1 className="font-serif text-xl sm:text-2xl font-bold text-[#191715] tracking-tight truncate max-w-md sm:max-w-xl">
              {document.name}
            </h1>
            <div className="flex items-center gap-2 text-xs font-mono text-[#7D766A]">
              <span>
                {document.pageCount} page{document.pageCount > 1 ? 's' : ''}
              </span>
              <span>·</span>
              <span>{document.wordCount.toLocaleString()} words</span>
              {document.fileSize && (
                <>
                  <span>·</span>
                  <span>{document.fileSize}</span>
                </>
              )}
            </div>
          </div>
        </div>

        {/* Action Controls */}
        <div className="flex items-center gap-2">
          <button
            onClick={() => setShowRawTextModal(true)}
            id="view-original-text-btn"
            title="View original extracted text"
            className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-[#4C463D] bg-white hover:bg-[#F4EFE6] border border-[#DCD6C9] rounded-lg transition-colors shadow-2xs cursor-pointer"
          >
            <Eye className="w-3.5 h-3.5" />
            <span>Raw Text</span>
          </button>
          <button
            onClick={handleCopySummary}
            id="copy-summary-btn"
            className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-[#4C463D] bg-white hover:bg-[#F4EFE6] border border-[#DCD6C9] rounded-lg transition-colors shadow-2xs cursor-pointer"
          >
            {copiedSummary ? <Check className="w-3.5 h-3.5 text-green-700" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copiedSummary ? 'Copied' : 'Copy'}</span>
          </button>
          <button
            onClick={handleDownloadMarkdown}
            id="download-markdown-btn"
            className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-[#4C463D] bg-white hover:bg-[#F4EFE6] border border-[#DCD6C9] rounded-lg transition-colors shadow-2xs cursor-pointer"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export .md</span>
          </button>
        </div>
      </div>

      {/* Main 2-Column Workspace Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        
        {/* Left Column (7 cols): Summary, Key Points, Topics */}
        <div className="lg:col-span-7 flex flex-col gap-8">
          
          {/* Executive Summary Section */}
          <div className="flex flex-col gap-3">
            <div className="flex items-center gap-2 text-sm font-semibold text-[#181615]">
              <span className="text-[#C4931A]">✦</span>
              <h2 className="font-serif text-xl font-bold tracking-tight text-[#181615]">
                Summary
              </h2>
            </div>
            
            {/* Highlighted warm card for the core synthesis */}
            <div className="p-5 sm:p-6 rounded-xl bg-[#F6F1E5]/80 border border-[#E9E1D2] shadow-2xs">
              <p className="text-[15px] sm:text-base text-[#2E2B27] leading-[1.65] font-serif whitespace-pre-line">
                {analysis.summary}
              </p>
            </div>
          </div>

          {/* KEY POINTS Section */}
          <div className="flex flex-col gap-3">
            <div className="flex items-center justify-between">
              <h3 className="text-xs font-mono font-bold tracking-widest text-[#7C766B] uppercase">
                KEY POINTS
              </h3>
              <span className="text-[11px] font-mono text-[#989182]">
                {analysis.keyPoints.length} items extracted
              </span>
            </div>

            <div className="flex flex-col gap-3">
              {analysis.keyPoints.map((point, idx) => (
                <div 
                  key={idx}
                  className="flex items-start gap-3 p-3.5 rounded-lg bg-white/70 border border-[#E6E0D4] hover:border-[#D5CDBE] transition-colors"
                >
                  {/* Amber square bullet marker matching video design */}
                  <span className="inline-block w-2.5 h-2.5 bg-[#E6BC4E] rounded-[2px] mt-1.5 shrink-0 shadow-3xs" />
                  <p className="text-sm text-[#2D2A26] leading-relaxed font-sans">
                    {point}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* TOPICS Section */}
          <div className="flex flex-col gap-3">
            <h3 className="text-xs font-mono font-bold tracking-widest text-[#7C766B] uppercase">
              TOPICS
            </h3>
            <div className="flex flex-wrap gap-2">
              {analysis.topics.map((topic, idx) => {
                const colorClass = topicColorStyles[idx % topicColorStyles.length];
                return (
                  <span
                    key={topic}
                    className={`px-3 py-1 text-xs font-medium rounded-full border shadow-3xs ${colorClass}`}
                  >
                    #{topic}
                  </span>
                );
              })}
            </div>
          </div>

          {/* Document Meta Tag Footer */}
          <div className="flex items-center justify-between pt-4 border-t border-[#E8E2D6] text-xs font-mono text-[#8C8578]">
            <span className="bg-[#EFEAE0] px-2.5 py-1 rounded-md text-[#5B554B] font-medium border border-[#DFD8CC]">
              {analysis.documentType} · 100% Extracted
            </span>
            <span>Précis Document Engine</span>
          </div>
        </div>

        {/* Right Column (5 cols): Interactive Q&A Assistant */}
        <div className="lg:col-span-5 flex flex-col bg-white/80 border border-[#E2DBD0] rounded-2xl shadow-xs overflow-hidden sticky top-20 max-h-[calc(100vh-6rem)]">
          
          {/* Q&A Header */}
          <div className="p-4 sm:p-5 border-b border-[#ECE6DB] bg-[#FAF8F3]">
            <div className="flex items-center gap-2 mb-1">
              <span className="text-[#C4931A]">✦</span>
              <h2 className="font-serif text-lg sm:text-xl font-bold text-[#181615]">
                Ask about this document
              </h2>
            </div>
            <p className="text-xs text-[#756E63] font-sans">
              Ask a question about the document and the answer will show up here, grounded in what you uploaded.
            </p>
          </div>

          {/* Q&A Chat Message Area */}
          <div className="flex-1 p-4 sm:p-5 overflow-y-auto min-h-[280px] max-h-[460px] flex flex-col gap-4">
            
            {chatMessages.length === 0 ? (
              /* Empty state guidance */
              <div className="flex flex-col items-center justify-center text-center my-auto py-6">
                <div className="w-10 h-10 rounded-full bg-[#F3EFE6] border border-[#DDD6C8] flex items-center justify-center text-[#827A6C] mb-3">
                  <HelpCircle className="w-5 h-5" />
                </div>
                <p className="text-xs text-[#7A7367] max-w-xs mb-4">
                  Ask anything specific — a figure, clause, decision, or summary detail.
                </p>
              </div>
            ) : (
              /* Conversation Messages */
              chatMessages.map((msg) => (
                <div
                  key={msg.id}
                  className={`flex flex-col ${
                    msg.role === 'user' ? 'items-end' : 'items-start'
                  }`}
                >
                  {msg.role === 'user' ? (
                    <div className="bg-[#1C1A18] text-[#F8F6F2] text-sm px-4 py-2.5 rounded-2xl rounded-tr-xs max-w-[85%] shadow-xs leading-relaxed font-sans">
                      {msg.content}
                    </div>
                  ) : (
                    <div className="flex flex-col gap-1 max-w-[95%]">
                      <span className="text-[10px] font-mono font-bold tracking-widest text-[#B8860B] uppercase">
                        PRÉCIS
                      </span>
                      <div className="bg-[#F8F5EE] border border-[#E7E0D3] text-[#24211D] text-sm p-4 rounded-2xl rounded-tl-xs shadow-3xs whitespace-pre-line leading-relaxed font-sans">
                        {msg.content}
                      </div>
                    </div>
                  )}
                </div>
              ))
            )}

            {/* Is asking indicator */}
            {isAsking && (
              <div className="flex flex-col gap-1 items-start max-w-[95%]">
                <span className="text-[10px] font-mono font-bold tracking-widest text-[#B8860B] uppercase">
                  PRÉCIS
                </span>
                <div className="bg-[#F8F5EE] border border-[#E7E0D3] text-[#696255] text-xs p-3.5 rounded-2xl rounded-tl-xs flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-[#B8860B] animate-pulse"></div>
                  <span>Searching document context & synthesizing answer...</span>
                </div>
              </div>
            )}

            <div ref={chatBottomRef} />
          </div>

          {/* Quick Prompt Suggestion Chips */}
          <div className="px-4 py-2 bg-[#F9F7F2] border-t border-[#ECE5D9] flex flex-wrap gap-1.5">
            {quickPrompts.slice(0, 3).map((prompt) => (
              <button
                key={prompt}
                onClick={() => handlePromptChipClick(prompt)}
                disabled={isAsking}
                className="text-[11px] font-medium text-[#504A40] bg-white hover:bg-[#EFE9DD] border border-[#DDD6C8] px-2.5 py-1 rounded-md transition-colors text-left truncate max-w-full cursor-pointer"
              >
                {prompt}
              </button>
            ))}
          </div>

          {/* Question Input Form */}
          <form onSubmit={handleSubmitQuestion} className="p-3 sm:p-4 bg-[#FAF8F3] border-t border-[#EAE3D6] flex gap-2">
            <input
              type="text"
              value={questionInput}
              onChange={(e) => setQuestionInput(e.target.value)}
              placeholder="e.g. What are the payment terms?"
              disabled={isAsking}
              id="qa-question-input"
              className="flex-1 px-3.5 py-2 text-sm bg-white border border-[#D9D2C4] rounded-lg focus:outline-none focus:ring-1 focus:ring-[#1E1C1A] text-[#1E1C1A] placeholder-[#9A9386]"
            />
            <button
              type="submit"
              disabled={!questionInput.trim() || isAsking}
              id="qa-submit-btn"
              className="px-4 py-2 bg-[#1C1A18] hover:bg-[#322F2B] disabled:opacity-40 text-[#F9F7F3] text-sm font-medium rounded-lg transition-colors flex items-center gap-1.5 shrink-0 cursor-pointer"
            >
              <span>Ask</span>
              <Send className="w-3 h-3" />
            </button>
          </form>
        </div>
      </div>

      {/* Raw Text Modal */}
      {showRawTextModal && (
        <div className="fixed inset-0 z-50 bg-black/40 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-[#FAF8F4] border border-[#D9D2C4] rounded-2xl max-w-3xl w-full max-h-[85vh] flex flex-col shadow-2xl overflow-hidden">
            <div className="p-4 sm:p-5 border-b border-[#E8E2D6] flex items-center justify-between bg-[#F5F1E8]">
              <div className="flex items-center gap-2">
                <BookOpen className="w-4 h-4 text-[#7A7367]" />
                <h3 className="font-serif font-bold text-lg text-[#181615]">
                  Extracted Document Text ({document.name})
                </h3>
              </div>
              <button
                onClick={() => setShowRawTextModal(false)}
                className="text-xs font-mono text-[#7D766A] hover:text-[#181615] px-2.5 py-1 bg-white border border-[#D4CDC0] rounded-md"
              >
                Close (ESC)
              </button>
            </div>
            <div className="p-5 overflow-y-auto flex-1 font-mono text-xs text-[#332F2A] whitespace-pre-wrap leading-relaxed bg-white/70 select-text">
              {document.text}
            </div>
            <div className="p-3 border-t border-[#E8E2D6] bg-[#F5F1E8] text-right">
              <span className="text-[11px] font-mono text-[#8C8476]">
                {document.pageCount} page(s) · {document.wordCount.toLocaleString()} words extracted
              </span>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
